### PR TITLE
HW1

### PR DESCRIPTION
**Pull request by Flock1**
Sarvagya Gupta's HW1

### CODE REVIEW

**Comment by JimmyWork668** [comment]
Good job, you need to fix the frequency for bouns problem. try to use nk.ecg_declineate function. 115

**Comment by Flock1** [comment]
Hi @JimmyWork668, I have used the function in the bonus question. Can you tell me if you can the function implemented in the cell with label `# TODO Let's filter the signal and see if the detection improves.`

**Comment by JimmyWork668** [comment]
@Flock1 Could you tell me your real name? I cannot find your information on Blackboard. Thanks

**Comment by Flock1** [comment]
@JimmyWork668 my real name is Sarvagya Gupta. But because of an error, it's showing as something like Sumaya Katane. I've talked to professor about this and he said it should've been solved. I'll talk to him after class today

**Comment by JimmyWork668** [comment]
@Flock1 Sorry, I still cannot find your information with Sumaya Katane on Blackboard. Could contact blackboard? when you finish the issue, please let us know. I will post your grade on the blackboard. Thank you

**Comment by JimmyWork668** [comment]
@Flock1 All parameters list below for the function:
    ecg_cleaned,
    rpeaks=None,
    sampling_rate=1000,
    method="dwt",
    show=False,
    show_type="peaks",
    check=False,
i don't think you can put a certain label directly.
https://neurokit2.readthedocs.io/en/latest/_modules/neurokit2/ecg/ecg_delineate.html

**Comment by Flock1** [comment]
@JimmyWork668, my name is updated on blackboard. Let me know if you can see it as "Sarvagya Gupta".

**Pull request closed without merging**
