### PR TITLE
02

### PR DESCRIPTION
**Pull request by yuva-01997656**
let's keep going.

### CODE REVIEW

**Comment by Jahnavi001** [comment]
100 Points
Bonus is not clear!

**Comment by yuva-01997656** [comment]
Is it 95 out of 100 or 100 points


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Jahnavi001** [comment]
Hi Yuva,

It’s 95 points. I will change the comment

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by yuva-01997656** [comment]
Hey Hii,
I rechecked the assignment and found that.. the code I used is correct but I mistakenly wrote wrong observations. So please look into this and consider the code and try to re-score my assignment.I here by request you to let me know if I could resubmit my assignment with right observations if needed .Do kindly help me out



With regards ,
Yuva Naga Sai Dinesh Vattikuti
01997656.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Jahnavi001** [comment]
Hi Yuva,

Can you please let me know which specific task you are referring?


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by yuva-01997656** [comment]
I’m referring task 1


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request closed without merging**
